baseurl: /
canonifyURLs: false
disableAliases: false
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
paginate: 7
rssLimit: 10

# Multilingual
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

# add redirects/headers
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
    - SITEMAP

# add output format for section sitemap.xml
outputFormats:
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap

caches:
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 10s

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  contributor: contributors

permalinks:
  blog: '/blog/:slug/'

minify:
  tdewolff:
    html:
      keepWhitespace: false

module:
  hugoVersion:
    extended: true
    min: 0.80.0
    max: ''
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: static/img
      target: assets/img
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/katex
      target: assets/js/vendor/katex
    - source: node_modules/mermaid
      target: assets/js/vendor/mermaid
