en:
  languageName: English
  contentDir: content/en
  weight: 10
  params:
    languageISO: EN
    languageTag: en-US
    dateFormat: "January 2, 2006"

es-us:
  languageName: Español
  contentDir: content/es-us
  weight: 15
  params:
    languageISO: ES
    languageTag: es-US
    dateFormat: "January 2, 2006"

zh-cn:
  languageName: 简体中文
  contentDir: content/zh-cn
  weight: 15
  hasCJKLanguage: true
  params:
    languageISO: ZH
    languageTag: zh-CN
    dateFormat: "2006年1月2日"
