# Meta Data for SEO

## Homepage
title: Aegisub
titleSeparator: '-'
titleAddition: Aegisub Advanced Subtitle Editor
description: >-
  Aegisub es una herramienta sin costo, agnóstica de plataforma y de código libre 
  para crear y modificar subtítulos. Aegisub facilita el proceso de sincronizar 
  subtítulos con audio y destaca muchas herramientas potentes para estilizarlos, 
  incluyendo una vista previa incrustada de video a tiempo real.

## Documentation
# docsVersion = "0.3"

## Open Graph
images:
  - img/logo.png
ogLocale: es_US
domainTLD: aegisub.org
titleHome: Aegisub

## Twitter Cards
twitterSite: '@aegisub'
#twitterCreator: '@henkverlinde'

## JSON-LD
# schemaType = "Person"
schemaType: Organization
schemaName: Aegisub
#schemaAuthor: Henk Verlinde
#schemaAuthorTwitter: 'https://twitter.com/henkverlinde'
#schemaAuthorLinkedIn: 'https://www.linkedin.com/in/henkverlinde/'
#schemaAuthorGitHub: 'https://github.com/h-enk'
schemaLocale: es-US
schemaLogo: logo-aegisub.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: img/logo-1280.png
schemaImageWidth: 1280
schemaImageHeight: 499
schemaTwitter: 'https://twitter.com/aegisub'
schemaLinkedIn: ''
schemaGitHub: 'https://github.com/Aegisub/Aegisub'
schemaSection: blog

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: '#fff'

# Images
quality: 85
bgColor: '#fff'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: '300'

# TODO: Maybe mention Hosting? NetworkRedux? Github Pages? Cloudflare Pages?
# Footer
footer: >-
  Powered by <a class="text-muted" href="https://gohugo.io/">Hugo</a> and <a
  class="text-muted" href="https://getdoks.org/">Doks</a>. <br/>
  Copyright (c) AegiSite <a href="https://github.com/Aegisub/aegisite/graphs/contributors">contributors</a>.

# Feed
# copyRight: Copyright (c) 2020-2021 Henk Verlinde

# Alert
alert: false
alertDismissable: true
alertText: >-
  Check out the cool new Aegisub Homepage!

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost: GitHub
#repoHost: "Gitea"
docsRepo: 'https://github.com/Aegisub/Aegisub'
docsRepoBranch: master
docsRepoSubPath: ''
editPage: false
lastMod: false

options:
  clipBoard: true
  instantPage: true
  flexSearch: false
  darkMode: true
  bootStrapJs: true
  breadCrumb: false
  highLight: true
  kaTex: false
  multilingualMode: true
  docsVersioning: false
  fullWidth: true
  navbarSticky: true
  toTopButton: false
  scrollSpy: false

menu:
  section:
    auto: false
    collapsibleSidebar: true
