# Meta Data for SEO

## Homepage
title: Aegisub
titleSeparator: '-'
titleAddition: Aegisub Advanced Subtitle Editor
description: >-
  Aegisub is a free, cross-platform open source tool for creating and modifying
  subtitles. Aegisub makes it quick and easy to time subtitles to audio, and
  features many powerful tools for styling them, including a built-in real-time
  video preview.

## Open Graph + Twitter Cards
images:
  - doks.png
twitterSite: henkverlinde
twitterCreator: henkverlinde
facebookAuthor: verlinde.henk
facebookPublisher: verlinde.henk
ogLocale: en_US

## JSON-LD
schemaType: Organization
schemaLogo: logo-doks.png
schemaTwitter: 'https://twitter.com/henkverlinde'
schemaLinkedIn: 'https://www.linkedin.com/in/henkverlinde/'
schemaGitHub: 'https://github.com/h-enk'
schemaSection: blog

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: '#fff'

# Images
quality: 85
bgColor: '#fff'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x

# footer/left side
footer: >-
  Powered by <a href="https://www.networkredux.com/">NetworkRedux</a>, <a
  href="https://gohugo.io/">Hugo</a>, and <a
  href="https://getdoks.org/">Doks</a>

# Alert
alert: false
alertText: >-
  Like Doks? <a class="alert-link"
  href="https://github.com/h-enk/doks/stargazers">Star on GitHub</a>.
  Thanks!</a>

# Edit Page
docsRepo: 'https://github.com/Aegisub/Aegisub'
editPage: false

options:
  lazySizes: true
  clipBoard: true
  instantPage: true
  flexSearch: true
  darkMode: true
  bootStrapJs: false
  breadCrumb: false
  highLight: true
  kaTex: false
